#!/usr/bin/env bash
##This script uses a while into an if statement to repeat text, with an edit to the ninth print
x=1
while [ $x -le 10 ]
do
	echo "Best School"
	if [ $x -eq 9 ]
	then
	    echo "Hi"
	fi
	((x++))
done
