#!/usr/bin/env bash
##This script uses a combination of a while loop and a longer if statement to display different itterations of text
## ...at certain points
x=1
while [ $x -le 10 ]
do
	if [ $x -eq 4 ]
	then
	    echo "bad luck"
	elif [ $x -eq 8 ]
	then
	    echo "good luck"
	else
	    echo "Best School"
	fi
	((x++))
done
