#!/usr/bin/env bash
##This script uses a while loop to display time for a set interval
hour=0
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minutes=1
	while [ $minutes -lt 60 ]
	do
	    echo "$minutes"
	    ((minutes++))
	done
	((hour++))
done
