#!usr/bin/env bash
##This script gives specific information about the file 'school'
##This script specifically uses both an if and an else with specific print outs for use cases
file="school"
if [ -e $file ]
then
	echo "$file file exists"

	if [ -s $file ]
	then
	    echo "$file file is not empty"
	else
	    echo "#file file is empty"
	fi

	if [ -f $file ]
	then
	    echo "$file is a regular file"
	fi
else
	echo "$file file does not exist"
fi
